### ISSUE TITLE
Error executing action `update` on resource 'nagios_resourcelist_items[update]'

### ISSUE THREAD

**Issue by GitBytes** [sous-chefs/nagios#351]
I seem to still be having an issue bringing in my service group stuff.. Can anyone verify this isn't still an issue from the providers angle? Thank you for your time. See output below, should be using the latest version since Merge #350. If I am possibly missing something that should fix this I am happy to try things.

```
 * nagios_resourcelist_items[update] action update[2015-03-27T20:55:51+00:00] INFO: Processing nagios_resourcelist_items[update] action update (nagios::default line 169)
==============================================================================
           Error executing action `update` on resource 'nagios_resourcelist_items[update]'
==============================================================================

           NoMethodError
           -------------
           undefined method `create' for Nagios::Servicegroup:Class

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/nagios/providers/resourcelist_items.rb:60:in `update_object'

       /tmp/kitchen/cache/cookbooks/nagios/providers/resourcelist_items.rb:46:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/nagios/providers/resourcelist_items.rb:21:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/nagios/recipes/default.rb

           169: nagios_resourcelist_items 'update'
           170: 

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/nagios/recipes/default.rb:169:in `from_file'

           nagios_resourcelist_items("update") do
             action :update
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :nagios_resourcelist_items
             cookbook_name "nagios"
             recipe_name "default"
           end

       [2015-03-27T20:55:51+00:00] INFO: Running queued delayed notifications before re-raising exception
       [2015-03-27T20:55:51+00:00] INFO: template[/etc/nagios/nagios.cfg] sending reload action to service[nagios] (delayed)
         * service[nagios] action reload[2015-03-27T20:55:51+00:00] INFO: Processing service[nagios] action reload (nagios::default line 197)
       [2015-03-27T20:55:51+00:00] INFO: service[nagios] reloaded

           - reload service service[nagios]

       Running handlers:
       [2015-03-27T20:55:51+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-03-27T20:55:51+00:00] ERROR: Exception handlers complete
       [2015-03-27T20:55:51+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 3 resources updated in 51.925204806 seconds
       [2015-03-27T20:55:51+00:00] ERROR: nagios_resourcelist_items[update] (nagios::default line 169) had an error: NoMethodError: undefined method `create' for Nagios::Servicegroup:Class
       [2015-03-27T20:55:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by sbotman** [comment]
Should have been fixed by last PR. See https://github.com/tas50/nagios/issues/347

**Comment by GitBytes** [comment]
Well, darn.. Sorry to open another issue on this. Not sure why this is still happening then.. Thanks for looking it over sir. I'll probably close this and do more testing and poking.. It was working until I attempted migrating to newest version(s), not sure what is wrong. I am assuming there wasn't something special to watch for between 6.1.2 and 7.0.4 on this..? Thanks in advance.

**Comment by sbotman** [comment]
I'm just pushing out 7.0.6 which should be working fine. Please let me know if you have problems with this version...

**Comment by GitBytes** [comment]
It would also help pulling from correct Berksfile source.. My mistake there but the test with 7.0.6 is coming back good! Thanks for the help! Closing now... Cheers!

**Comment by sbotman** [comment]
Tnx for closing. I have pushed 7.0.6 to the supermarket! Cheers Sander
